# 应用服务 WEB 访问端口
server:
  port: 8000
  servlet:
    context-path: /apis
spring:
  cache:
    type: redis
    cache-names: blog
  datasource:
    url: jdbc:mysql://101.34.69.172:3306/blog
    username: root
    password: qazwsxedc123..
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: Blog-ldx
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    port: 6379
    database: 15
    host: 101.34.69.172
    password: qazwsxedc123..
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


cache:
  ttl: '{"user":60,"dept":30}'  #自定义某些缓存空间的过期时间
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

logging:
  level:
    com.ldx.blog: debug
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: litubao_authentication
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 3600
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
#网站域名
website:
  config:
    url: https://www.lidengxiang.top/
    cdn: https://lidengxiang.top/
qiniuyunwebsite: https://lidengxiang.top/
### 七牛云
qiniuyun:
  accessKeyId: FRMyr6yfm88JgtXwjILNam_uomMzbWOk7WrDWzjh
  secret: P8rPFTvtJ-RJrQDD5ORMLFdO0j9xw7gOGpeo4dib
qq:
  client_id: 102024615
  client_secret: OeleJjvsZ6PVN1Qa
  redirect_url: https%3A%2F%2Fwww.lidengxiang.top%2Fcallback
mq:
  SMS_EXCHANGE: SMSCODE_EXCHANGE
  SMS_QUEUE: SMSCODE_QUEUE
  SMS_ROUTING_KEY: SMS
phone:
  VALIDATE_CODE: SMS_159620392
  ORDER_NOTICE: SMS_159771588
  DEFAULT_NOTICE: SMS_257771439