spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog
    username: root
    password: qazwsxedc123..
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    database: 14
    host: 101.34.69.172
    password: qazwsxedc123..
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
files:
  path: files/
redirect:
  url: "https://www.lidengxiang.top/#/loading/"
  error-page: "https://www.lidengxiang.top/#/login"
logging:
  level:
    com.ldx.blog: error
