/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleDetailHeader: typeof import('./components/ArticleDetailHeader.vue')['default']
    MarkDownCpt: typeof import('./components/MarkDownCpt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitArticleDlg: typeof import('./components/dlg/SubmitArticleDlg.vue')['default']
    TagInput: typeof import('./components/TagInput.vue')['default']
  }
}
